MoDNN: MNIST Class Reference
MNIST Class Reference
#include <mnist.h>
Public Member Functions
MNIST (char *images_file, char *labels_file, bool shuffle=false)
size_t getInputDim ()
size_t getLabelDim ()
size_t getDatasetSize ()
void get_item (int index, float *data, float *label)
void get_item_range (int start, int end, float *data_batch, float *label_batch)
Private Member Functions
void parse_labels_file (char *labels_file)
void parse_images_file (char *images_file)
void shuffle ()
Private Attributes
std::vector< std::vector< float > > images
std::vector< float > labels
unsigned seed
Additional Inherited Members
Protected Attributes inherited from Dataset
size_t dataset_size_
size_t input_size_
size_t label_size_
Detailed Description
Definition at line 7 of file mnist.h.
Constructor & Destructor Documentation
MNIST::MNIST (char * images_file, char * labels_file, bool shuffle = false)
Definition at line 13 of file mnist.cpp.
References images, Dataset::label_size_, labels, parse_images_file(), parse_labels_file(), and seed.
{
     if (shuffle)
         seed = std::chrono::system_clock::now().time_since_epoch().count();
     label_size_ = 1;
     parse_images_file(images_filename);
     parse_labels_file(labels_filename);
     if (shuffle){
         std::shuffle(images.begin(), images.end(), std::default_random_engine(seed));
         std::shuffle(labels.begin(), labels.end(), std::default_random_engine(seed));
     }
 }
Member Function Documentation
void MNIST::get_item (int index, float * data, float * label) virtual
Implements Dataset.
Definition at line 99 of file mnist.cpp.
References images, Dataset::input_size_, Dataset::label_size_, and labels.
{
     memcpy(data, images[index].data(), sizeof(float)*input_size_);
     memcpy(label, &labels[index], sizeof(float)*label_size_);
 }
void MNIST::get_item_range (int start, int end, float * data_batch, float * label_batch) virtual
Implements Dataset.
Definition at line 104 of file mnist.cpp.
References images, Dataset::input_size_, Dataset::label_size_, and labels.
{
     for (int i = start; i < end; i++){
         memcpy(data_batch+(i-start)*input_size_, images[i].data(), sizeof(float)*input_size_);
         memcpy(label_batch+(i-start)*label_size_, &labels[i], sizeof(float)*label_size_);
     }
 }
size_t MNIST::getDatasetSize () virtual
Implements Dataset.
Definition at line 95 of file mnist.cpp.
References Dataset::dataset_size_.
{
     return dataset_size_;
 }
size_t MNIST::getInputDim () virtual
Implements Dataset.
Definition at line 87 of file mnist.cpp.
References Dataset::input_size_.
{
     return input_size_;
 }
size_t MNIST::getLabelDim () virtual
Implements Dataset.
Definition at line 91 of file mnist.cpp.
{
     return 10;
 }
void MNIST::parse_images_file (char * images_file) private
Definition at line 37 of file mnist.cpp.
References Dataset::dataset_size_, images, Dataset::input_size_, and reverseBits().
Referenced by MNIST().
{
     std::ifstream fd(images_file, std::ios::in | std::ios::binary);
     char data[4];
     unsigned int magic_number, rows, cols, i = 0;
     char pixel;
     fd.read(data, sizeof(unsigned));
     magic_number = reverseBits(*((unsigned int*) data));
     fd.read(data, sizeof(unsigned));
     dataset_size_ = reverseBits(*((unsigned int*) data));
     fd.read(data, sizeof(unsigned));
     rows = reverseBits(*((unsigned int*) data));
     fd.read(data, sizeof(unsigned));
     cols = reverseBits(*((unsigned int*) data));
     input_size_ = rows*cols;
     std::cout << input_size_ << " " << rows << " " << cols << " " << dataset_size_ << std::endl;
     images.resize(dataset_size_);
     data[0] = 0;
     data[1] = 0;
     data[2] = 0;
     while(!fd.eof()) {
         images[i].resize(input_size_);
         for (int j = 0; j < input_size_; j++) {
             fd.read(&data[3], 1);
             images[i][j] = reverseBits(*((unsigned int*) data))/255.0;
         }
         i++;
     }
     fd.close();
 }
void MNIST::parse_labels_file (char * labels_file) private
Definition at line 67 of file mnist.cpp.
References Dataset::dataset_size_, labels, and reverseBits().
Referenced by MNIST().
{
     std::fstream fd;
     unsigned int magic_number, i = 0;
     char value;
     char data[4];
     fd.open(label_file, std::ios::in | std::ios::binary);
     fd.read(data, sizeof(unsigned));
     magic_number = reverseBits(*((unsigned int*) data));
     fd.read(data, sizeof(unsigned));
     dataset_size_ = reverseBits(*((unsigned int*) data));
     labels.resize(dataset_size_);
     while(!fd.eof()) {
         fd.read(&value, 1);
         labels[i] = int(value);
         i++;
     }
     fd.close();
 }
void MNIST::shuffle () private virtual
Implements Dataset.
Definition at line 30 of file mnist.cpp.
References images, and labels.
 {
   unsigned seed_temp = std::chrono::system_clock::now().time_since_epoch().count();
   std::shuffle(images.begin(), images.end(), std::default_random_engine(seed_temp));
   std::shuffle(labels.begin(), labels.end(), std::default_random_engine(seed_temp));
 }
Field Documentation
std::vector<std::vector<float> > MNIST::images private
Definition at line 9 of file mnist.h.
Referenced by get_item(), get_item_range(), MNIST(), parse_images_file(), and shuffle().
std::vector<float> MNIST::labels private
Definition at line 10 of file mnist.h.
Referenced by get_item(), get_item_range(), MNIST(), parse_labels_file(), and shuffle().
unsigned MNIST::seed private
Definition at line 14 of file mnist.h.
Referenced by MNIST().
The documentation for this class was generated from the following files:
mnist_dataset/mnist.h
mnist_dataset/mnist.cpp