MoDNN: layers/layers.h File Reference
layers.h File Reference
#include "../vmm/vmm.h"
#include <cudnn.h>
#include <vector>
#include <queue>
#include <string>
#include <iostream>
#include <sstream>
#include <map>
#include <cublas_v2.h>
#include <cassert>
#include <cstdlib>
#include <random>
#include <cuda.h>
#include <fstream>
Data Structures
class layers::Layer
Abstract class Layer.
class network::seqNetwork
Main neural network class.
Namespaces
layers
Contains all function and classes involving neural network layers.
network
Contains all function and classes involving initialization training of neural networks.
Macros
#define MU 0
#define SIGMA 0.1
#define LR 0.0001
#define BATCH_SIZE 128
#define TILE_SIZE 32
#define BLOCK_SIZE 8
#define checkCUDNN(expression)
#define checkCUBLAS(expression)
#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }
Enumerations
enum padding_type { SAME, VALID }
Functions
const char * cublasGetErrorString (cublasStatus_t error)
void gpuAssert (cudaError_t code, const char *file, int line, bool abort=true)
std::map< std::string, float * > init_buffer_map ()
__global__ void SoftmaxLossBackprop (const int *label, int num_labels, int batch_size, float *diff)
__global__ void matrixMultiplyShared (float *A, float *B, float *C, int numARows, int numAColumns, int numBRows, int numBColumns, int numCRows, int numCColumns)
__global__ void transposeCoalesced (float *odata, const float *idata, int idata_rows, int idata_cols)
__global__ void matrixMultiplyNaive (float *A, float *B, float *C, int N, int K, int M)
__global__ void transposeNaive (float *odata, const float *idata, int idata_rows, int idata_cols)
__global__ void update (float *weights, float *grad, float lr, int N)
int calc_bytes_from_shape (int shape[])
Macro Definition Documentation
#define BATCH_SIZE 128
Definition at line 28 of file layers.h.
#define BLOCK_SIZE 8
Definition at line 30 of file layers.h.
#define checkCUBLAS (expression)
Value:
{                                                          \
    cublasStatus_t status = (expression);                     \
    if (status != CUBLAS_STATUS_SUCCESS) {                    \
      std::cerr << "Error on line " << __LINE__ << ": "      \
                << cublasGetErrorString(status) << std::endl; \
      std::exit(EXIT_FAILURE);                               \
    }                                                        \
  }
Definition at line 45 of file layers.h.
#define checkCUDNN (expression)
Value:
{                                                          \
    cudnnStatus_t status = (expression);                     \
    if (status != CUDNN_STATUS_SUCCESS) {                    \
      std::cerr << "Error on line " << __LINE__ << ": "      \
                << cudnnGetErrorString(status) << std::endl; \
      std::exit(EXIT_FAILURE);                               \
    }                                                        \
  }
Definition at line 33 of file layers.h.
#define gpuErrchk (ans) { gpuAssert((ans), __FILE__, __LINE__); }
Definition at line 56 of file layers.h.
Referenced by print_arr(), and random_populate_float().
#define LR 0.0001
Definition at line 27 of file layers.h.
#define MU 0
Definition at line 25 of file layers.h.
#define SIGMA 0.1
Definition at line 26 of file layers.h.
#define TILE_SIZE 32
Definition at line 29 of file layers.h.
Enumeration Type Documentation
enum padding_type
Enumerator
SAME
VALID
Definition at line 19 of file layers.h.
                  {
   SAME,
   VALID
 };
Function Documentation
int calc_bytes_from_shape (int shape[])
Referenced by gpuAssert().
const char* cublasGetErrorString (cublasStatus_t error)
void gpuAssert (cudaError_t code, const char * file, int line, bool abort = true) inline
Definition at line 57 of file layers.h.
References calc_bytes_from_shape(), init_buffer_map(), matrixMultiplyNaive(), matrixMultiplyShared(), SoftmaxLossBackprop(), transposeCoalesced(), transposeNaive(), and update().
 {
    if (code != cudaSuccess)
    {
       fprintf(stdout,"GPUassert: %s %s %d\n", cudaGetErrorString(code), file, line);
       if (abort) exit(code);
    }
 }
std::map<std::string,float*> init_buffer_map ()
Referenced by gpuAssert().
__global__ void matrixMultiplyNaive (float * A, float * B, float * C, int N, int K, int M)
Naive Matrix Multiplication kernel.
Referenced by gpuAssert().
__global__ void matrixMultiplyShared (float * A, float * B, float * C, int numARows, int numAColumns, int numBRows, int numBColumns, int numCRows, int numCColumns)
Matrix Multiplication kenel using shared memory and tiling.
Referenced by gpuAssert().
__global__ void SoftmaxLossBackprop (const int * label, int num_labels, int batch_size, float * diff)
Softmax backpropagation kernel.
Parameters
label Ground truth label.
Referenced by gpuAssert().
__global__ void transposeCoalesced (float * odata, const float * idata, int idata_rows, int idata_cols)
Kernel to find transpose of a matrix using coalesing.
Referenced by gpuAssert().
__global__ void transposeNaive (float * odata, const float * idata, int idata_rows, int idata_cols)
Kernel to find transpose of a matrix in a naive way.
Referenced by gpuAssert().
__global__ void update (float * weights, float * grad, float lr, int N)
Updates the parameters of neural network.
Parameters
weights Parameters to update.
grad Gradients of parameters.
lr Learning rate.
N Num of parameters.
Referenced by gpuAssert().